# Generated by Django 3.2.7 on 2021-10-31 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puestos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puesto',
            name='puestos_llenos',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='puestos_totales',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='puestos_vacios',
            field=models.IntegerField(null=True),
        ),
    ]
