# Generated by Django 3.2.7 on 2021-10-31 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puestos', '0002_auto_20211031_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puesto',
            name='puestos_llenos',
        ),
        migrations.RemoveField(
            model_name='puesto',
            name='puestos_totales',
        ),
        migrations.RemoveField(
            model_name='puesto',
            name='puestos_vacios',
        ),
        migrations.AddField(
            model_name='puesto',
            name='ocupado',
            field=models.BooleanField(null=True),
        ),
    ]
