# Generated by Django 3.2.7 on 2021-11-01 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puestos', '0005_auto_20211031_1856'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Puesto',
        ),
    ]
