# Generated by Django 3.2.7 on 2021-11-01 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puestos', '0007_puesto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puesto',
            options={'verbose_name': 'Puesto', 'verbose_name_plural': 'Puestos'},
        ),
    ]
