# Generated by Django 3.2.9 on 2021-11-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puestos', '0012_alter_puesto_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puesto',
            name='contenido',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='puestos'),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='ocupado',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='titulo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
